package com.example.controllers;

public enum AdminAction {
    CREATE_CATEGORY,
    CREATE_ACTIVITY,
    GET_ALL_USERS,
    GET_ALL_USERS_THEIR_ACTIVITIES_AND_TIME,
    GET_ALL_CATEGORIES,
    GET_ALL_ACTIVITIES,
    GET_ALL_ACTIVITIES_SORTED_BY_USERS,
    GET_ALL_ACTIVITIES_SORTED_BY_CATEGORY,
    GET_ALL_ACTIVITIES_SORTED_BY_NAME,
    GET_PENDING_REQUESTS,
    DECLINE_REQUEST,
    CONFIRM_REQUEST,
    SIGN_OUT;

}
