package com.example.controllers;

public enum UserAction {
    //    CREATE_CATEGORY,
    //    CREATE_ACTIVITY,
    ADD_ACTIVITY_REQUEST,
    REMOVE_ACTIVITY_REQUEST,
    SET_TIME_TO_ACTIVITY,
    GET_CATEGORIES,
    GET_ALL_ACTIVITIES,
    GET_ALL_ACTIVITIES_FILTERED_BY_CATEGORY,
    GET_MY_ACTIVITIES,
    GET_MY_ACTIVITIES_SORTED_BY_DURATION,
    GET_MY_ACTIVITIES_FILTERED_BY_CATEGORY,
    GET_MY_TOTAL_TIME,
    SIGN_OUT;

}
